apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicure-deployment
  labels:
    app: medicure
spec:
  replicas: 2
  selector:
    matchLabels:
      app: medicure
  template:
    metadata:
      labels:
        app: medicure
    spec:
      containers:
      - name: medicure
        image: hillol111/medicure:1.0
        ports:
        - containerPort: 80

